<?php

namespace AppBundle;

/**
 * MmebreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MmebreRepository extends \Doctrine\ORM\EntityRepository
{
}
