<?php



namespace AppBundle\Repository;

use AppBundle\Entity\Produit;

/**
 * ProduitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProduitRepository extends \Doctrine\ORM\EntityRepository
{

    // create Query: 
    public function getAllCategories2() {

        $em -> getEntityManager();
        $query = $em -> createQuery("SELECT DISTINCT(p.categorie) FROM AppBundle\Entity\Produit p ORDER BY p.categorie ASC"); // normally we would put produit, but doctrine doesnt work with tables and works only with objects - entities / with ORDER BY we have made that the categories will go by the letter
        $categories = $query -> getResult(); // it's an equivalent to the fetch assoc
        return $query -> getResult();

        }
        // Query Builder:

        public function getAllCategories(){ 

        $em = $this -> getEntityManager();
        $query = $em -> createQueryBuilder();
        $query
             -> select('p.categorie')
             -> distinct(true)
             -> from(produit::class, 'p')
             -> orderBy('p.categorie', 'ASC');

            //  SELECT DISTINCT(categorie) FROM produit p ORDER BY categorie ASC
            $categories = $query -> getQuery() -> getResult();
            return $query -> getQuery() -> getResult();

 }
}
